export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const HANDLE_SIGNUP_CHANGE = 'HANDLE_SIGNUP_CHANGE';
export const HANDLE_FILTER_CHANGE = 'HANDLE_FILTER_CHANGE';
export const SET_SIGNUP_DEFAULTS = 'SET_SIGNUP_DEFAULTS';
export const RESET_SIGNUP_FIELDS = 'RESET_SIGNUP_FIELDS';
export const RESET_FILTER_FIELDS = 'RESET_FILTER_FIELDS';

export const HANDLE_TOKEN_CHANGE = 'HANDLE_TOKEN_CHANGE';
