export const SHOW_CURRENT_FEE_TYPE = 'SHOW_FEE_TYPE';
export const SHOW_CURRENT_FEE_TYPE_SUCCESS = 'SHOW_FEE_TYPE_SUCCESS';
export const SHOW_CURRENT_FEE_TYPE_FAILURE = 'SHOW_FEE_TYPE_FAILURE';
export const SET_FEE_TYPE_DEFAULTS = 'SET_FEE_TYPE_DEFAULTS';
export const HANDLE_FEE_TYPE_CHANGE = 'HANDLE_FEE_TYPE_CHANGE';
export const VALIDATE_FEE_TYPE_FORM = 'VALIDATE_FEE_TYPE_FORM';
export const CREATE_FEE_TYPES = 'CREATE_FEE_TYPES';
export const CREATE_FEE_TYPES_SUCCESS = 'CREATE_FEE_TYPES_SUCCESS';
export const CREATE_FEE_TYPES_FAILURE = 'CREATE_FEE_TYPES_FAILURE';
export const EDIT_FEE_TYPES = 'EDIT_FEE_TYPES';
export const EDIT_FEE_TYPES_SUCCESS = 'EDIT_FEE_TYPES_SUCCESS';
export const EDIT_FEE_TYPES_FAILURE = 'EDIT_FEE_TYPES_FAILURE';

export const LIST_FEE_TYPES = 'LIST_FEE_TYPES';
export const LIST_FEE_TYPES_SUCCESS = 'LIST_FEE_TYPES_SUCCESS';
export const LIST_FEE_TYPES_FAILURE = 'LIST_FEE_TYPES_FAILURE';

export const DELETE_FEE_TYPES = 'DELETE_FEE_TYPES';
export const DELETE_FEE_TYPES_SUCCESS = 'DELETE_FEE_TYPES_SUCCESS';
export const DELETE_FEE_TYPES_FAILURE = 'DELETE_FEE_TYPES_FAILURE';