export const SHOW_CURRENT_FEE = 'SHOW_FEE';
export const SHOW_CURRENT_FEE_SUCCESS = 'SHOW_FEE_SUCCESS';
export const SHOW_CURRENT_FEE_FAILURE = 'SHOW_FEE_FAILURE';
export const SET_FEE_DEFAULTS = 'SET_FEE_DEFAULTS';
export const HANDLE_FEE_CHANGE = 'HANDLE_FEE_CHANGE';
export const VALIDATE_FEE_FORM = 'VALIDATE_FEE_FORM';
export const CREATE_FEES = 'CREATE_FEES';
export const CREATE_FEES_SUCCESS = 'CREATE_FEES_SUCCESS';
export const CREATE_FEES_FAILURE = 'CREATE_FEES_FAILURE';
export const EDIT_FEES = 'EDIT_FEES';
export const EDIT_FEES_SUCCESS = 'EDIT_FEES_SUCCESS';
export const EDIT_FEES_FAILURE = 'EDIT_FEES_FAILURE';

export const LIST_FEES = 'LIST_FEES';
export const LIST_FEES_SUCCESS = 'LIST_FEES_SUCCESS';
export const LIST_FEES_FAILURE = 'LIST_FEES_FAILURE';