export const SHOW_CURRENT_STUDENT = 'SHOW_STUDENT';
export const SHOW_CURRENT_STUDENT_SUCCESS = 'SHOW_STUDENT_SUCCESS';
export const SHOW_CURRENT_STUDENT_FAILURE = 'SHOW_STUDENT_FAILURE';
export const SET_STUDENT_DEFAULTS = 'SET_STUDENT_DEFAULTS';
export const HANDLE_STUDENT_CHANGE = 'HANDLE_STUDENT_CHANGE';
export const VALIDATE_STUDENT_FORM = 'VALIDATE_STUDENT_FORM';
export const TESTING = 'TESTING';
export const CREATE_STUDENTS = 'CREATE_STUDENTS';
export const CREATE_STUDENTS_SUCCESS = 'CREATE_STUDENTS_SUCCESS';
export const CREATE_STUDENTS_FAILURE = 'CREATE_STUDENTS_FAILURE';
export const EDIT_STUDENTS = 'EDIT_STUDENTS';
export const EDIT_STUDENTS_SUCCESS = 'EDIT_STUDENTS_SUCCESS';
export const EDIT_STUDENTS_FAILURE = 'EDIT_STUDENTS_FAILURE';

export const LIST_STUDENTS = 'LIST_STUDENTS';
export const LIST_STUDENTS_SUCCESS = 'LIST_STUDENTS_SUCCESS';
export const LIST_STUDENTS_FAILURE = 'LIST_STUDENTS_FAILURE';

export const DELETE_STUDENTS = 'DELETE_STUDENTS';
export const DELETE_STUDENTS_SUCCESS = 'DELETE_STUDENTS_SUCCESS';
export const DELETE_STUDENTS_FAILURE = 'DELETE_STUDENTS_FAILURE';