export const SHOW_CURRENT_TEACHER = 'SHOW_TEACHER';
export const SHOW_CURRENT_TEACHER_SUCCESS = 'SHOW_TEACHER_SUCCESS';
export const SHOW_CURRENT_TEACHER_FAILURE = 'SHOW_TEACHER_FAILURE';
export const SET_TEACHER_DEFAULTS = 'SET_TEACHER_DEFAULTS';
export const HANDLE_TEACHER_CHANGE = 'HANDLE_TEACHER_CHANGE';
export const VALIDATE_TEACHER_FORM = 'VALIDATE_TEACHER_FORM';
export const CREATE_TEACHERS = 'CREATE_TEACHERS';
export const CREATE_TEACHERS_SUCCESS = 'CREATE_TEACHERS_SUCCESS';
export const CREATE_TEACHERS_FAILURE = 'CREATE_TEACHERS_FAILURE';
export const EDIT_TEACHERS = 'EDIT_TEACHERS';
export const EDIT_TEACHERS_SUCCESS = 'EDIT_TEACHERS_SUCCESS';
export const EDIT_TEACHERS_FAILURE = 'EDIT_TEACHERS_FAILURE';

export const LIST_TEACHERS = 'LIST_TEACHERS';
export const LIST_TEACHERS_SUCCESS = 'LIST_TEACHERS_SUCCESS';
export const LIST_TEACHERS_FAILURE = 'LIST_TEACHERS_FAILURE';

export const DELETE_TEACHERS = 'DELETE_TEACHERS';
export const DELETE_TEACHERS_SUCCESS = 'DELETE_TEACHERS_SUCCESS';
export const DELETE_TEACHERS_FAILURE = 'DELETE_TEACHERS_FAILURE';