export const SHOW_CURRENT_USER = 'SHOW_USER';
export const SHOW_CURRENT_USER_SUCCESS = 'SHOW_USER_SUCCESS';
export const SHOW_CURRENT_USER_FAILURE = 'SHOW_USER_FAILURE';
export const SET_USER_DEFAULTS = 'SET_USER_DEFAULTS';
export const HANDLE_USER_CHANGE = 'HANDLE_USER_CHANGE';
export const TESTING = 'TESTING';
export const EDIT_USERS = 'EDIT_USERS';
export const EDIT_USERS_SUCCESS = 'EDIT_USERS_SUCCESS';
export const EDIT_USERS_FAILURE = 'EDIT_USERS_FAILURE';

export const DELETE_USERS = 'DELETE_USERS';
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS';
export const DELETE_USERS_FAILURE = 'DELETE_USERS_FAILURE';
